"""empty message

Revision ID: 0b41af171cef
Revises: 315b7184bf1f
Create Date: 2019-02-27 18:57:38.208760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b41af171cef'
down_revision = '315b7184bf1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=240), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user', sa.String(length=240), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ratings')
    # ### end Alembic commands ###
