"""empty message

Revision ID: 1b43a5bc7f5f
Revises: 86061edd368b
Create Date: 2019-02-27 00:28:54.739322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b43a5bc7f5f'
down_revision = '86061edd368b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('date', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'date')
    # ### end Alembic commands ###
