"""empty message

Revision ID: 315b7184bf1f
Revises: 
Create Date: 2019-02-27 01:11:44.457188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315b7184bf1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=240), nullable=True),
    sa.Column('mes', sa.String(length=240), nullable=True),
    sa.Column('date', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
