"""empty message

Revision ID: 75b5a1a21d12
Revises: 
Create Date: 2019-03-03 14:30:17.769349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b5a1a21d12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=240), nullable=True),
    sa.Column('followed_nickname', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=240), nullable=True),
    sa.Column('mes', sa.String(length=240), nullable=True),
    sa.Column('date', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=240), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user', sa.String(length=240), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ratings')
    op.drop_table('messages')
    op.drop_table('followers')
    # ### end Alembic commands ###
